name: Build and deploy ASP.Net Core app to Azure Web App - monitorapplication

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish the app
      run: dotnet publish -c Release --output ./output/myapp

    - name: List files in output
      run: ls ./output/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'monitorapplication'  # Ditt App Service-namn
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Använder secret
        package: './output/myapp'

    - name: Check DOTNET_ROOT
      run: echo $DOTNET_ROOT
